### PR TITLE
Fix Temperature

### LINKED ISSUE #60: Fix temperature
Temperature's implementation is faulty, and unit tests are written badly, i'm fixing it right now.

### PR DESCRIPTION
**Pull request by michelececcacci**
Fixes #60

### CODE REVIEW

File: app/src/test/java/homer/common/TemperatureTest.java [hunk 1]
```diff
@@ -10,6 +10,7 @@
  */
 public final class TemperatureTest {
     private final TemperatureFactory factory = new TemperatureFactoryImpl();
+    private final double delta = 0.01f;
```
Comment (aleemont1) [inline app/src/test/java/homer/common/TemperatureTest.java:13]: Is this a constant? If so i think it should be
```suggestion
    private final static double DELTA = 0.01f;
```

**Review by aleemont1 — APPROVED** [review]
Just the doubt about `delta`
